version: 2.1

orbs:
  node: electronjs/node@2.2.0

executors:
  windows:
    machine:
      image: windows-server-2022-gui:2023.11.1
      resource_class: windows.medium
      shell: bash.exe

jobs:
  win-test:
    executor: windows
    steps:
      - run: conda info

workflows:
  build-and-test:
    jobs:
      - win-test
